-- ══════════════════════════════════════════
-- TechStore — Consultas Básicas SELECT
-- Autor: Adrian Santiago Agustin Vera
-- Fecha: 12/08/2026
-- ══════════════════════════════════════════
-- Consulta 1: Exploración general de la tabla sales
SELECT * FROM sales;
-- Consulta 2: Selección de columnas específicas para finanzas
SELECT customer_id, product_id, total_amount 
FROM sales;
-- Consulta 3: Selección con alias en español para stakeholders
SELECT order_date AS "fecha_pedido", product_name AS "nombre_producto", quantity AS "cantidad_unidades"
FROM sales;

-- CONSULTA 1: EXPLORACION GENERAL
/* ES RECOMENDABLE UTILIZAR DICHA CONSULTA PARA VISUALIZAR TODAS LAS COLUMNAS QUE CONFORMAN LA TABLA
AL IGUAL QUE PODER TENER UNA VISIÓN GENERAL DE LOS REGISTROS QUE LA TABLA POSEE. NO OBSTANTE ES RECOMENDABLE
LIMITAR LA CANTIDAD DE REGISTROS CON TOP EN CASO DE QUE FUERA UN GRAN VOLUMEN DE REGISTROS.*/

-- CONSULTA 2: SELECCION ESPECIFICA
/* ES UNA CONSULTA EN LA CUAL SE ELIGEN LAS COLUMNAS QUE SE DESEAN MOSTRAR, ESTO PERMITE EVITAR UNA VISUALIZACION MAS TRANSPARENTE
EVITANDO RECUPERAR DATOS INECESARIOS */

-- CONSULTA 3: NOMBRES AMIGABLES CON ALIAS
/* EN UNA CONSULTA ES POSIBLE REEMPLAZAR EL NOMBRE ENCABEZADO DE UNA COLUMNA HACIENDO USO DE ALIAS. ESTO PERMITE REESTRUCTURAR LOS 
NOMBRES DE LOS ENCABEZADOS POR UNA VISUALIZACION MAS FRIENDLY PARA AQUELLOS USUARIOS QUE NO POSEEN UNA COMPRENCION TECNICA */
